#!/bin/bash

# Copyright (c) 2019 Benjamin Holt -- MIT License

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
usage: listb              List git branches that have different local vs. remote
                          names (like ones created with newb)
       listb -h|--help    Print this message and exit
USAGE
    exit 0
fi

ConfigRemote=`git config allgit.defaultremote`
: ${AllgitRemote:=${ConfigRemote:-"origin"}}

# Delete lines where the local branch matches the remote branch (ignoring ahead/behind annotations like "[origin/master: behind 86]")
# git branch -vv | sed -e '/^[* ] \([^ ][^ ]*\)  *[a-fA-F0-9][a-fA-F0-9]*  *\['$AllgitRemote'\/\1\(:.*\)*\]/d'  # REM: for some reason, I couldn't get backrefs to work in extended re :-/
# Delete lines *other than the current branch* where...
git branch -vv | sed -e '/^  \([^ ][^ ]*\)  *[a-fA-F0-9][a-fA-F0-9]*  *\['$AllgitRemote'\/\1\(:.*\)*\]/d'  # REM: for some reason, I couldn't get backrefs to work in extended re :-/

Bold=`tput bold`
Off=`tput sgr0`
echo "${Bold}DEPRECATED: This tool was moved${Off} https://github.com/inventhouse/bettergit"

###
