#!/bin/bash

# Copyright (c) 2019 Benjamin Holt -- MIT License

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
usage: newb SLUG [ALIAS]   Creates a new git branch named ALIAS and immediately
                           pushes it to a remote branch named prefix/SLUG
                           ALIAS defults to initials from the SLUG
       newb -h|--help      Print this message and exit
USAGE
    exit 0
fi

if [ -z "$1" ]; then
    echo "Must specify a slug for the new branch name" >&2
    exit 1
fi

Slug="$1"
# Alias="${2:-`echo "$Slug" | sed -e 's:.*/::'`}"  # Derrive default alias from last segment of the slug
Alias="${2:-`echo "$Slug" | sed -e 's/[A-Z]*-[0-9]*//' | tr -d 'a-z0-9_.-' | tr 'A-Z' 'a-z'`}"  # Derive default alias from UpperCaseInitials (ignoring any JIRA-123- prefix)
if [ -z "$Alias" ]; then
  Alias=`echo "$Slug" | sed -e 's:.*/::g' -e 's/[A-Z][A-Z]*-[0-9][0-9]*//' -e 's/^\([A-Za-z]\)[^_.-]*/\1/' -e 's/[_.-]\([A-Za-z]\)[^_.-]*/\1/g'`  # Derive default alias from dash-separated-initials (again ignoring JIRA-123-)
fi

Branch=`git branch --list "$Alias"`
if [ "$Branch" ]; then
    echo "$Alias: branch already exists" >&2
    exit 1
fi

git checkout -b "$Alias"
setupb "$Slug" "$Alias"

###
