#!/bin/bash

# Copyright (c) 2019 Benjamin Holt -- MIT License

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
usage: setupb [SLUG [ALIAS]]   Pushes a local branch (ALIAS) to a remote branch
                               named prefix/SLUG; use once to set the upstream,
                               then just push normally
       setupb -h|--help        Print this message and exit
USAGE
    exit 0
fi

Alias="${2:-${ALLGIT_BRANCH:-`git rev-parse --abbrev-ref HEAD`}}"
Slug="${1:-$Alias}"

if [ -z "$Alias" ]; then
    echo "Must specify a branch directly, using allgit, or the current branch" >&2
    exit 1
fi

Branch=`git branch --list "$Alias"`
if [ -z "$Branch" ]; then
    echo "$Alias: branch not found" >&2
    exit 1
fi

ConfigRemote=`git config allgit.defaultremote`
: ${AllgitRemote:=${ConfigRemote:-"origin"}}

Upstream=`git rev-parse --abbrev-ref "$Alias@{upstream}" 2> /dev/null | sed -e "s:$AllgitRemote/::"`
if [ "$Upstream" ]; then
    echo "$Alias: already pointing to $Upstream" >&2
    exit 1
fi

if `echo "$Slug" | grep "/" - > /dev/null`; then
    git push -u "$AllgitRemote" "$Alias:$Slug"  # If slug is already prefixed, use as-is
    exit 0
fi

: ${BranchPrefix:=`git config allgit.branchprefix`}
PrefixMessage="change it with: git config --global allgit.branchprefix 'users/abc'"
if [ -z "$BranchPrefix" ]; then
    BranchPrefix=`git config user.shortname`
    echo "Using prefix $BranchPrefix/ $PrefixMessage"
fi
if [ -z "$BranchPrefix" ]; then
    BranchPrefix=`git config user.name | tr 'A-Z ' 'a-z_'`
    echo "Using prefix $BranchPrefix/ $PrefixMessage"
fi
if [ -z "$BranchPrefix" ]; then
    BranchPrefix="$USER"
    echo "Using prefix $BranchPrefix/ PrefixMessage"
fi

BranchPrefix=`echo "$BranchPrefix"  | sed -e's:/$::'`  # Trim any trailing slash to ensure isn't doubled
git push -u "$AllgitRemote" "$Alias:$BranchPrefix/$Slug"

###
