#!/bin/bash

# For a git repo, stash changes, pull with rebase, and pop the stashed changes back
# Copyright (c) 2018 Benjamin Holt -- MIT License

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
usage: stashpull [REPO]     Pulls with rebase and autostash REPO.
       stashpull -h|--help  Print this message and exit
USAGE
    exit 0
fi

pushd "${1:-.}" >> /dev/null

git pull --rebase=true --autostash  # Turns out git has this built-in, just use that

popd >> /dev/null

###
