#!/bin/bash

# For a git repo, stash changes, pull with rebase, and pop the stashed changes back
# Copyright (c) 2018 Benjamin Holt -- MIT License

if [ "$1" == "-h" -o "$1" == "--help" ]; then
    cat <<USAGE
usage: stashpull [REPO]     Stashes changes and pulls (with rebase) REPO, then
                            pops the stashed changes back.
       stashpull -h|--help  Print this message and exit
USAGE
    exit 0
fi

pushd "${1:-.}" >> /dev/null

Status=`git status -s | egrep -v '^\?\?'`  # Untracked files, with status ??, don't get stashed; just look for "stashable" changes
if [ "$Status" ]; then
  git stash
fi

git pull --rebase=true

if [ "$Status" ]; then
  git stash pop
fi

popd >> /dev/null

###
